### ISSUE TITLE
How can I measure the throughput of prads?

### ISSUE THREAD

**Issue by asvcer** [gamelinux/prads#49]
Hello, how can I measure the throughput of prads? Can prads benefits from a multi-core CPU? Thank you!

**Comment by comotion** [comment]
Hm. This may no longer be relevant to the original submitter, considering how long you've waited for an answer, however there are a number of ways to measure performance and someone else might stumble upon this issue. I've run multi-gigabyte pcap files and seen how long prads takes to process them on a given machine. I've also snarfed gigabit interfaces and seen if prads manages to stay on the ball.

You can use BPF filters and/or network interface segregation to run multiple instances of prads to take advantage of several cores. Prads is single-threaded for a number of reasons, however it is known to handle gigabit traffic on one single instance. A version of prads that can take advantage of multi-core CPUs was planned, and a lot of the code has been written with this in mind, but never deemed neccessary (at least for the users that chimed in).

Feel free to reopen if you want to discuss this further.

**Comment by asvcer** [comment]
Thank you for answering my question.
